import {BaseColor, StatusColor} from '@/constants';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cardContainer: {
    flex: 0.5,
    display: 'flex',
    width: '100%',
    height: 'auto',
    borderRadius: 8,
    backgroundColor: BaseColor.White,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowColor: '#C9C9C9',
    elevation: 5,
    padding: 4,
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 4,
  },
  contentCard: {
    marginVertical: 8,
    marginHorizontal: 8,
  },
  content: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemContent: {
    flex: 2.5 / 3,
  },
  location: {
    marginTop: 4,
    flex: 1 / 3,
    flexDirection: 'row',
    gap: 4,
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: BaseColor.MiddleGray,
    marginVertical: 8,
  },
  priceContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  discount: {
    width: 'auto',
    height: 20,
    borderRadius: 50,
    padding: 4,
    display: 'flex',
    alignSelf: 'center',
    backgroundColor: StatusColor.Error,
  },
  cardContainerHorizontal: {
    flex: 0.5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 270,
    height: 70,
    borderRadius: 8,
    backgroundColor: BaseColor.White,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowColor: '#C9C9C9',
    elevation: 5,
    padding: 4,
  },
  imageHorizontal: {
    width: 64,
    height: 64,
    borderRadius: 4,
  },
  contentHorizontal: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 8,
  },
  star: {
    marginTop: 4,
    flex: 1 / 3,
    flexDirection: 'row',
    gap: 4,
  },
  dividerHorizontal: {
    width: '100%',
    height: 1,
    backgroundColor: BaseColor.MiddleGray,
    marginVertical: 4,
  },
  priceContainerHorizontal: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 4,
  },
});
